name: Build

on:
  push:
    branches:
      - master
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Debug Environment Variables
        run: |
          echo "DEBUG: The username Gradle will use is: ${PACKAGE_GITHUB_USER}"
          echo "DEBUG: The user running this workflow is: ${{ github.actor }}"
          echo "DEBUG: The repository is: ${{ github.repository }}"
          echo "DEBUG: ${PACKAGE_GITHUB_TOKEN: -3}"
        env:
          PACKAGE_GITHUB_USER: ${{ secrets.PACKAGES_READ_USER }}
          PACKAGE_GITHUB_TOKEN: ${{ secrets.PACKAGES_READ_TOKEN }}
      - name: Build
        run: ./gradlew build
        env:
          PACKAGE_GITHUB_USER: "akashgoto24"
          PACKAGE_GITHUB_TOKEN: ${{ secrets.PACKAGES_READ_TOKEN }}